travis:
  secure:
    BINSTAR_TOKEN: M3s9xiFRsicvqhObF10rzycFB7SIn2u47IaewcWIsgV605jYZxmCIx399G8teu5GEuvR8nrT/4ULx30KZFo1YfSQyOw+FPFroxF9gclhWdoQ6hN/zUhY97pLI4x5YeypyOU3gLUm4kqoEK+W23bS4R9bXOtNaA145wH7Lq2P87bNal04hZSYD5+3QGY4yzSXQImL+7YFSCwnn6M2DLfxOPs01ueRNuhSSJ19j6eSeBVknlP8uhJO77oKsOErMC8gGbaimw+02olMxGaLO5p9/O0TpQEglTTumnDBFVgVOuLizpYT2psWteMjTG2QIQOTGeE9kFNqFIus1b9qzw0wXRDphTF0h5b78FA68PLQ1qwmHpOh7xJGOqlek2X7s2VQTprRvHmNSzfGtBQZLmmCn8j3s2LSzJnJna8OlmLjQ/dNGhU6KnrevLAhlRZ2ez1ejhLSDZ7Jg9VT1qB+EKVn5GL8art5QCtC5THLowl2nx5+HN1u1SGOhQh9+o3yGi8jUQmEC57OY0EKudt5Jp7ys2GVCVTJDvuccXmFEbGQj+FUm9nKJM6XVvqoTUH9wv7yPlvMp+GsDXR3bCG8bE7n1PNapC/imCIISJp3RFrmkRie+udO8x66JKaxHxrb7pGF5ytZxn+C+5dfaVTTXOU/vJSkwGWgSWkEJaAU1bp+tMo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
