travis:
  secure:
    BINSTAR_TOKEN: bv+X7EtdgxB9f90Xu0NkdBlj7kgq91Tux/wSkEJ7AdIcHvrw+zOjNATXglGjHTYZZOVgX7xVrFeT7DGD2BeJB3N3mGoieNAqFEsN73bkD2oLyjGejVjw85PfU+VZ6QLiw/wRZyudXWrx2OTkVddjEUzUgr7AYiM9SZ7rer/WetMv2k53UvB8qlkoXbLCWOrS89QmzLFhJ28wOrXQLD5J7+rJexsF3Wzu9C2Xx3CFRlaZwhp5+LvaoOFzhjEJHmuik1mWzg665SDRzN6uVKG8gbOhR+jkYQIqL+x2VTb5NErh563zn2IzjsQ77Xo8oJYs6htmuBDnEyJulT9GaHTKQy+G7sMTbG/XT+bHR1xdaMl12z0sr1mmeveiyd5Xpdx456GPraMkhxDtvfXp9CDWsvlRVjH4O6mwhYBFg/DRWzf9dqVe9WtKG27JEKAmhElyRuNGGm4JxGXG/w8DLZ+E6YfpER+GRB2y4TuT695be7Erv4RG1qWJq3+tZOgtyJVXNCnRSwepwkIFi5KsYEmb4WFHPXLH5EHzFw1f5ijpZBuP7pwDXBxSf9QAA0fDugKkF4MJoHsuEJ6XkSAe62RTOOoc8YyrWrDZdrOjtEPrfjUi0tVvD6t/AkS3N+aGTYFXREgorl0fbs4XF/lkZ5jw2XlFM6SwEJJf9R7TXqPamGk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
