travis:
  secure:
    BINSTAR_TOKEN: pjMN46O/SLVwtN4s8nGeYDPzxk02yys9ApYV7ToYFbGAbTW1y8KtlrqXrRRxC3xblaHIPDYj4pJCZQnPaI4vhXHIMfihxq+xdZHLerV66VH29NxcyYAN6bxyekpENUak5hOVSnf4KzOdTZPhjrK3Ei8y6gOakL2WRo35VXKDALUExJ6hK8rLwCeMMlQZXgZBqigmSenJfAB/+DyQCV589mO47kD81A9iOYsckuZM2I35vV4/Z526z41BojuY+IlzrO5pNLUg3gZirHO4bdwamFLSDyi4nNh3DJqNgUtCy0YJRL95nAHOLMkA0Nnuk6RiD4xbZjfNhNtgF27oLagzTEBMd0Tj6vE2Y1+3/xipmgDtVn9KLYX9cA4XfLwPH9ObcGjGb28MGq9VS4j07DlKt6hMiIMziZJdNDqYqeZaRJ/QzJDhq6kVYKoCqBTcvPPhfYBvOGhDX8ayjorbinYA238tPHJ5yesx8m8UcESmAJf2bdiYt8Ve9WkcZdB0kwqTPCFumIcTqFHLgKdJS/HgKjgE3wOlLvDSHwy6/csvrEt4AwDrQ0b/sXjckfFVRfmpmbalgQtjYe1slQH1xBWQA975UQAedyf3/Y526GR9Oe4M5qqNy9sNce0yH4zFdGOkopPx5Vd4z/YNPO9Y6QJFxbc5O1uQ0SwhtbQXssaGp1Q=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
