travis:
  secure:
    BINSTAR_TOKEN: Po4S6FFzOL6FRJEICNPpHz2xXgHtmGI8NeE69G4qZ5NfcSxkX4n6yS5bIUOSx6tMHBBfuI2rx+WGmAlTAsBQjTgOwOhqhpdIOIJ/EzaCne7dMD0y6cbIK0st1yuGH/SHh+GSH71haY48N6ylmbyjhNw1voDYQHfM/lC63h1KCTuDsFCSuPcYTl8e8KUzTT0i35CM3ZsJcvZuD+s23F717h6omWoZBU2Uc03M/imgmGwoqigiKjcBt8g3y+Vc75NmUD6a3DryjdtlgBOmKtqX7C8CYt98+ynwpp3ubYwr8pHHGm6F7FxctplVFRHkknOJAowbXoYhmW1z3Q7f34Y+KYcnIEKHYpRFCdOH1vVie8NYyhhnLnjKlXVsNEVg7dLIDEyvyC7MlwDy456qjH/+sykOFSoGxPALDmIvWY2f2tFF4890MR/oK5QsZcD6r8uOP7tNc8y1aDq5CxxF2oJQz/ijJiAxk4492sXoc6tMqW9k6vbvfpjoCtbik/mXh/H7PRfEANmmM7WxxzGPDEoubAZBSZ1E3o9XegtnGCV3sBnyTzJwwLBlZo+r0e6PJvgCWsHdd2rOiErHGAKrgH9/P3XLApARx2FXVAscnaT7ZNUVkRH+2gEY/+bctvw04ltdvJMfaGZEf15vXo3IwWWWok6rgy5DeMTZMzSMCaLI5no=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
